---
title: "Peyton_work"
output: html_document
---


Normalize data to use the same words
```{r}
words <- read.csv("wordbank_instrument_data.csv")
data <- read_csv("wordbank_administration_data.csv")
filtered_data <- data %>% select(child_id, is_norming, age, typically_developing)

child_words <- inner_join(words, filtered_data, by = "child_id")

#Child 1 is a norming CDI set 
CDI_words <- child_words %>% filter(child_id == 1)
CDI_words <- unique(CDI_words$english_gloss)
child_CDI_words <- child_words %>% filter(english_gloss %in% CDI_words)

# tot_words_norming <- tot_words %>% filter(is_norming) %>% group_by(child_id) %>% count
# tot_words_not_norming <- tot_words %>% filter(!is_norming) %>% group_by(child_id) %>% count
# print(tot_words)
tot_CDI_words <- child_CDI_words %>% group_by(child_id) %>%
  summarise(unique_count = n_distinct(english_gloss[value == "produces"]), age = max(age.x), typically_developing = min(typically_developing))
```

Graph the data 
```{r}
atypical <- tot_CDI_words %>% filter(!typically_developing) %>%
  transform(age_boxes = ifelse(age <= 12, "8-12", ifelse(age <= 20, "13-20", ">20")))
ggplot(data = atypical, aes(x = age_boxes, y = unique_count)) + geom_boxplot() +
  labs(x = "Age Range (months)", y = "Number of Words Learned", title = "Distribution of Words Learned by Age Range")

plot3 <- ggplot(data = atypical, aes(x = age)) + geom_histogram() +
  labs(x = "Age (months)", y = "Count", title = "Distibution of Atypically Developing Children by Age")
ggsave("age_dist.png", plot = plot3, width = 7, height = 5, units = "in", dpi = 300)
```

```{r}
tot_CDI_words2 <- tot_CDI_words %>% transform(typically_developing = ifelse(typically_developing == 1,"Typically Developing", "Atypical Development"))
plot3<-ggplot(tot_CDI_words2, aes(x = age, y = unique_count, color = typically_developing)) + geom_point(alpha = 0) + geom_jitter(width = .5, height = .5, alpha = .3) +
  labs(x = "Age Range (months)", y = "Number of Words Learned", title = "Distribution of Words Learned by Age Range", color = "Development") + geom_smooth(se = FALSE, method = "lm")
ggsave("dist_age_v_words_scatter.png", plot = plot3, width = 7, height = 5, units = "in", dpi = 300)
```


S curve of words learned at 22-25 months
```{r}
  words_in_age_range <- tot_CDI_words %>% filter(age<=25) %>% filter(age>=22)
  plot4 <- ggplot(data = words_in_age_range, aes(x = unique_count, y = typically_developing)) + geom_jitter(width = 0.5, height = 0.1) +geom_hline(yintercept=mean(words_in_age_range$typically_developing),color="red") + geom_smooth(formula = y ~ x, method = "glm",
method.args=list(family="binomial"),se=FALSE,color="blue", alpha = 0.5) + labs(x = "Number of Words Learned at 22-25 months", y = "Typically Developing", title = "Words Learned vs Development", color = "Development")
  
  ggsave("logistic_words.png", plot = plot4, width = 7, height = 5, units = "in", dpi = 300)

```


